package models

import "time"

type User struct {
	ID       int64     `json:"id" db:"id"`
	Name     string    `json:"name" db:"name"`
	Phone    string    `json:"phone" db:"phone"`
	Role     string    `json:"role" db:"role"`
	Password string    `json:"password" db:"password"`
	Created  time.Time `json:"created_at" db:"created_at"`
}

type UserRequest struct {
	Name     string    `json:"name"`
	Phone    string    `json:"phone"`
	Role     string    `json:"role"`
	RoleId   int       `json:"role_id"`
	Password string    `json:"password"`
	Created  time.Time `json:"created_at"`
}

type AutoGenerated struct {
	UsdPhp struct {
		Val float64 `json:"val"`
	} `json:"USD_PHP"`
}
